spring:
  application:
    name: medilab-address-service
  cloud:
    config:
      uri: http://localhost:8888      
server:
  port: 9060
springdoc:
  swagger-ui:
    enabled: true
    path: /addr-doc.html
  api-docs:
    enabled: true
    path: /addr-api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
user: 
 data:
  duplicate: 
    message: The Data submitted may have already existed. Please check the data and submit once again
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-address-service
    #docker url
    #url: jdbc:mysql://medilab-user-service-mysql:3306/medilab-user-store
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true    
  config:
    activate:
      on-profile: dev
---
spring:
  h2:
    console:
      enabled: true
      path: /h2Console
  config:
    activate:
      on-profile: stage