spring:
  application:
    name: medilab-department-service

#  h2:
#    console:
#      enabled: true
#      path: /h2Console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-department-db
    username: root
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    
springdoc:
  swagger-ui:
    path: /department-doc.html
    
management:
  endpoints:
    web:
      exposure:
        include: '*'  
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true 

server:
  port: 5001
