spring:
  application:
    name: medilab-department-service
  profiles:
    active: stage
server:
  port: 9098
springdoc:
  swagger-ui:
    enabled: true
    path: /department-doc.html
  api-docs:
    enabled: true
    path: /department-api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
user: 
 data:
  duplicate: 
    message: The Data submitted may have already existed. Please check the data and submit once again
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-department-service
    #url: jdbc:mysql://medilab-user-service-mysql:3306/medilab-user-store
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: stage
  h2:
    console:
      enabled: true
      path: /h2Console
server:
  port: 9099